### ISSUE TITLE
Just curious: API info

### ISSUE THREAD

**Issue by frankhommers** [stefboerrigter/plugwise-python#1]
Where did you get the API info? By docs (I want them too) or by reverse engineering the GUI?

**Comment by stefboerrigter** [comment]
http://domoticx.com/plugwise-smile-p1-links-en-bestanden/ and reverse engineering the XML data. 
But sadly my plugwise isn't working as expected. If plugwise cannot satisfy me with a working Adam + lisa i'm going to return the products to them and stop work also on this plugin.

**Comment by frankhommers** [comment]
I moved on to Home Assistant, and I was wondering if there's a plugin for HA. (Or maybe write it myself). Anyway, as it seems, are there also reverse engineered API's to e.g. switch a plug?

**Comment by stefboerrigter** [comment]
Not sure if there is, i know for Domoticz there is a plug for switching Plugs etc. 
I'm reverse engineering this for Heating control. 
See also https://github.com/stefboerrigter/com.plugwise.adam (forked) (i guess also reverse engineered) API on switching Plugs and setting temperatures

**Comment by riemers** [comment]
@frankhommers https://github.com/laetificat/haanna has a python module for Anna. Just asked him for adam support https://github.com/laetificat/haanna/issues/1 see also my findings there. It is possible to get some data out but it requires loops through multiple devices. Anna is just one. 

Custom component for HA same guy :) https://github.com/laetificat/anna-ha although i have not managed to get any further then to get some data in:
![image](https://user-images.githubusercontent.com/682041/53204953-37da6a80-362d-11e9-8c6c-750632ec4572.png)

Still shows anna, but this is from my adam. (with only 1 lisa in it) just taggint people along to see if we can work something out. (after all a python module can help HA and domoticz)

**Comment by frankhommers** [comment]
Ah cool stuff. I will check it out!

**Comment by stefboerrigter** [comment]
Just for your information; i shipped the plugwise stuff back to the shop, wasn't working for me so no further development to be expected from my side but feel free to fork it and continue yourself

**Comment by riemers** [comment]
What didn't work then? Perhaps its a show stopper for me too then.

**Comment by stefboerrigter** [comment]
I used plugwise adam with my Nefit Ecomline HR (On/OFF). but appearantly the ON-OFF still uses some open-therm communication with a high resistance on the wires to check if there is some heating appliance available using open-therm. This background communication causes my Nefit to start heating continously. 
This was not solved so i decided to return the devices to the shop for a refund.
API / app was working pretty good, Lisa and Adam where working also pretty good, only not with my boiler.

**Comment by riemers** [comment]
I have city heating which uses on/off, problem there was that from their point of view the radiators never need closing because if the 'boiler' is turned of, so do the radiators. But since my boiler is city heating it doesn't get turned off. Called them up and they changed something remotely which now turns off the radiators when the city heating is suppose to be turned off (Sort of speak)

I think that will be in the upcoming updates so for me they did more then i had thought. (could be just lucky because it was coming anyway)

Too bad it didn't came on time for you, since like you mentioned too, lisa/adam works just fine.

**Comment by riemers** [comment]
p.s. did you have the adapter in between the nefit?

**Comment by stefboerrigter** [comment]
No, no adapter, i used plain On-Off. 
Used a scope to determine that there was something happening on the wires (on-off) when the Adam would be off. Had frequent contact but no response on this topic, unsure if they are aware of this themselves. Even after sending video evidence they still answered that it should just work. So then i decided to build my own setup.

**Comment by riemers** [comment]
Ah because nefit says its opentherm but they are just a little bit different. Friend of mine told me that nefit needs a adapter to talk "opentherm" so it works with plugwise (which uses the real opentherm format) as far as i am told.

**Comment by stefboerrigter** [comment]
Correct, Nefit uses their own EMS protocol. There is an Nefit EMS <-> Opentherm adapter available, but it uses a subset of opentherm. It is not supported by Plugwise. Therefore only ON/OFF is supported for this boiler.

**Comment by riemers** [comment]
Reading a bit on nefit and opentherm is like walking into a hornets nest i see on the internet. Well i learned one thing now, if i ever have a different house stay away from nefit it looks like :) Either way i did send plugwise a mail that it should support all.

**Comment by stefboerrigter** [comment]
Nefit is a fine brand, newer boilers (mine is from 1995 or so) have full OpenTherm support so no issue there. 
Back before OpenTherm was widely used all boilers used either ON-OFF or started developing their own 'custom' protocol for modulating boilers as Nefit did with their EMS protocol.  
The issue is that with new techniques, you still have legacy devices working on the old technique. 

If Plugwise would have really implemented ON-OFF (ON == shortcut the wires with a resitor in between, OFF = create an open connection; example use a Relay), i would have no issue. the problem is that during OFF the connection between the wires is open for ~1 second, then 4K resistance for ~1 second and then open again (etc.) My guess was that this was communication on Open-Therm in the back-ground. So the blame is on Plugwise rather than Nefit.

**Comment by riemers** [comment]
I do have a direct contact at plugwise, i could just report it see what they say. But i presume you already did similar steps. (just trying to help here, you did already send it back so don't know if it has value for you)

And well if the Nefit is from 1995, i presume they made stuff beter these days.

**Comment by stefboerrigter** [comment]
Feel free to ask, i'm still curious on what they say but i never got an answer on this topic, i could forward you an e-mail if you like with more details and a movie. Technically i would like them to fix it :)

**Comment by riemers** [comment]
Why not, send me one.

**Comment by stefboerrigter** [comment]
You (should) have an e-mail.

**Comment by riemers** [comment]
Got it

**Comment by frankhommers** [comment]
Hey @stefboerrigter I got the same central heater in my office. Ecomline HR. I stumbled upon this: https://shop.hotgoodies.nl/ems/ check it out (including GitHub link). I am going to try this.

For my house I use an Adam HA and an Open Therm central heater.

**Comment by stefboerrigter** [comment]
I saw the EMS conversion board, it will not be sufficient to convert Nefit Ecomline HR EMS to Opentherm, it also is no good for any conversion to ON/OFF.
The issue remains; 
 1. Plugwise didn't implement ON-OFF sufficient for the Ecomline HR (or sufficient at all)
 2. Nefit Ecomline HR is not suitable (even with converters) for OpenTherm.

**Comment by frankhommers** [comment]
I ordered the EMS board, but it didn't work on Ecomline. The Ecomline (at least the classic, doesn't talk EMS). Now I will test it soon in combination with a moduline 400 thermostat and a nefit easy connect. I am confident that that way I am able to control it remotely.

Anyway, I have seen people getting the Ecomline HR to talk opentherm: https://www.klusidee.nl/Forum/toon-thermostaat-en-nefit-hr-excellent-t103745.html

**Comment by stefboerrigter** [comment]
Did you check if it communicates using the EMS protocol only? or did you check if any bytes are beeing received? i read somewhere that it might be that Ecomline HR uses an 'older protocol' compared to EMS. Since the EMS board only does voltage leveling between Ecomline (230V) and Pi (3/5V) you should be able to see communication / bytes passing by?

**Comment by frankhommers** [comment]
I managed to make it all work by putting an "Nefit Easy Connect" in the middle. Read all about it here: https://github.com/proddy/EMS-ESP/issues/133

**Comment by stefboerrigter** [comment]
Sounds great, I'll have a try as well. Find an unused converter module.


Op vr 21 jun. 2019 15:23 schreef Frank Hommers <notifications@github.com>:
